### ISSUE TITLE
not work Android 14

### ISSUE THREAD

**Issue by hdk2d** [Pzqqt/com.androidemu.nes_61#1]
Won't install on Android 14 says unsupported application

**Comment by Pzqqt** [comment]
> Won't install on Android 14 says unsupported application

Newer Android systems have taken installation restrictions on APKs whose target ABI is too low.
The target API of Nesoid's original apk is 9, corresponding to Android 2.3, which is obviously too old.
But you can still install it via adb command or shell/root privileges.
